[package]
name = "pixelflut_fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(unix)'.dependencies]
pixelflut = { path = "..", features = ["tokio", "memory-cache", "windowed"] }
afl = "0.12"
